const foodItems = [
  "almonds",
  "apple",
  "banana",
  "bitter gourd",
  "broccoli",
  "butter",
  "capsicum",
  "carrot",
  "chana dal",
  "chapathi",
  "cheese",
  "chicken breast",
  "chickpeas",
  "coconut oil",
  "curd",
  "drumstick",
  "eggs",
  "ghee",
  "grapes",
  "kiwi",
  "lady finger",
  "lentils",
  "mango",
  "masoor dal",
  "milk",
  "moong dal",
  "naan",
  "oats",
  "olive oil",
  "orange",
  "paneer",
  "papaya",
  "paratha",
  "peanut butter",
  "pineapple",
  "pomegranate",
  "potato",
  "quinoa",
  "rice",
  "salmon",
  "spinach",
  "strawberry",
  "sunflower oil",
  "sweet potato",
  "tofu",
  "toor dal",
  "tuna",
  "urad dal",
  "water",
  "watermelon",
  "wheat bread",
  "whey protein",
  "yogurt"
];

export default foodItems;
