const foodItems = [
  "almonds",
  "apple",
  "appam",
  "banana",
  "bitter gourd",
  "broccoli",
  "butter",
  "capsicum",
  "carrot",
  "chana dal",
  "chapathi",
  "cheese",
  "chicken breast",
  "chickpeas",
  "coconut oil",
  "curd",
  "dosa",
  "drumstick",
  "eggs",
  "Finger Millet Malt",
  "ghee",
  "grapes",
  "idli",
  "kiwi",
  "lady finger",
  "lentils",
  "mango",
  "masala dosa",
  "masoor dal",
  "milk",
  "moong dal",
  "naan",
  "oats",
  "olive oil",
  "orange",
  "paneer",
  "papaya",
  "paratha",
  "peanut butter",
  "pesarattu",
  "pineapple",
  "pomegranate",
  "pongal",
  "potato",
  "quinoa",
  "rava dosa",
  "rice",
  "salmon",
  "spinach",
  "strawberry",
  "sunflower oil",
  "sweet potato",
  "tofu",
  "toor dal",
  "tuna",
  "upma",
  "urad dal",
  "uthappam",
  "vada",
  "water",
  "watermelon",
  "wheat bread",
  "whey protein",
  "yogurt"
];

export default foodItems;
