const foodItems = [
  "oats",
  "rice",
  "wheat bread",
  "quinoa",
  "chapathi",
  "paratha",
  "naan",
  "whey protein",
  "chicken breast",
  "eggs",
  "tuna",
  "salmon",
  "tofu",
  "paneer",
  "peanut butter",
  "lentils",
  "chickpeas",
  "almonds",
  "toor dal",
  "moong dal",
  "masoor dal",
  "urad dal",
  "chana dal",
  "milk",
  "yogurt",
  "curd",
  "cheese",
  "potato",
  "carrot",
  "spinach",
  "broccoli",
  "sweet potato",
  "capsicum",
  "drumstick",
  "bitter gourd",
  "lady finger",
  "apple",
  "banana",
  "orange",
  "pomegranate",
  "mango",
  "grapes",
  "pineapple",
  "watermelon",
  "papaya",
  "kiwi",
  "strawberry",
  "olive oil",
  "coconut oil",
  "sunflower oil",
  "ghee",
  "butter",
  "water",
];

export default foodItems;
